# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cca9bc9c0a79a1117e56b08149ce86bb07827621b3ddeb4a4fc56cfeb2f3b97294beec5869920f90950cad33ccce201e576069ae49e81a307842b84b93689e66

test:
  secret_key_base: db5a6add5eebdabb6b9382d72392077ccb208a0b126f6c0330678937c3246f1ba016931ae19e5195fd55ced12f4c4bfa64ad6c3cdc82c6ab69592d48c4924f94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
